### ISSUE TITLE
Problem if "id" is not the name of the primary key column

### ISSUE THREAD

**Issue by SebHoremans** [CircleOfNice/DoctrineRestDriver#51] opened 2017-04-21 14:08 UTC
Hi, 
first thanks for your awesome job.

The API I use doesn't named "id" the "column" name for the primary key. It is prefixed like that : 
usr_id for the users
sit_id for the sites
cpy_id for the companies
etc.

When I use direct SQL connection there's no problem because the column name is declare with : 
/**
     * @ORM\Id
     * @ORM\Column(type="integer", name="usr_id")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

But with the Rest driver it doesn't works correctly.
The result is that I get request like GET : "/users?usr_" 
Thanks for your help.

**Comment by SebHoremans** [comment] 2017-05-08 10:24
A small re-up because this problem stopped our project for now.

**Comment by TobiasHauck** [comment] 2017-05-08 10:27
Hey maybe you can help solving this problem. May you please check where the name of the field is cut? I think the tokenizer is causing this issue.

Thank you!

**Comment by SebHoremans** [comment] 2017-05-08 10:52
Hello,
When the id field is set on usr_id the driver try to reach /users/usr_

I'm searching in your files why is it like that.

**Comment by SebHoremans** [comment] 2017-05-08 11:45
Don't know if it helps but I added some logs in the "execute" function (circle/doctrine-rest-driver/Circle/DoctrineRestDriver/Statement.php) and I get a strange thing : 

I made a log of $this->query  before the "setParams", before the "transformRequest" and a log after the "transformRequest"

Here is the log : `"SELECT t0.usr_id AS usr_id_1, t0.usr_firstname AS usr_firstname_2, t0.usr_lastname AS usr_lastname_3, t0.usr_phone AS usr_phone_4, t0.usr_mobile AS usr_mobile_5, t0.usr_picture AS usr_picture_6, t0.usr_function AS usr_function_7, t0.usr_added_date AS usr_added_date_8, t0.usr_last_update_date AS usr_last_update_date_9, t0.usr_username AS usr_username_10, t0.usr_username_canonical AS usr_username_canonical_11, t0.usr_password_requested_at AS usr_password_requested_at_12, t0.usr_roles AS usr_roles_13, t0.usr_email AS usr_email_14, t0.usr_email_canonical AS usr_email_canonical_15, t0.usr_enabled AS usr_enabled_16, t0.usr_salt AS usr_salt_17, t0.usr_password AS usr_password_18, t0.usr_last_login AS usr_last_login_19, t0.usr_confirmation_token AS usr_confirmation_token_20, t0.usr_added_by AS usr_added_by_21, t0.usr_last_modified_by AS usr_last_modified_by_22, t0.usr_workspace AS usr_workspace_23 FROM users t0 WHERE t0.usr_username_canonical = ? LIMIT 1"

"SELECT t0.usr_id AS usr_id_1, t0.usr_firstname AS usr_firstname_2, t0.usr_lastname AS usr_lastname_3, t0.usr_phone AS usr_phone_4, t0.usr_mobile AS usr_mobile_5, t0.usr_picture AS usr_picture_6, t0.usr_function AS usr_function_7, t0.usr_added_date AS usr_added_date_8, t0.usr_last_update_date AS usr_last_update_date_9, t0.usr_username AS usr_username_10, t0.usr_username_canonical AS usr_username_canonical_11, t0.usr_password_requested_at AS usr_password_requested_at_12, t0.usr_roles AS usr_roles_13, t0.usr_email AS usr_email_14, t0.usr_email_canonical AS usr_email_canonical_15, t0.usr_enabled AS usr_enabled_16, t0.usr_salt AS usr_salt_17, t0.usr_password AS usr_password_18, t0.usr_last_login AS usr_last_login_19, t0.usr_confirmation_token AS usr_confirmation_token_20, t0.usr_added_by AS usr_added_by_21, t0.usr_last_modified_by AS usr_last_modified_by_22, t0.usr_workspace AS usr_workspace_23 FROM users t0 WHERE t0.usr_username_canonical = root LIMIT 1"

GET http://localhost:8000/users?usr_username_canonical=root HTTP/1.1


---------------------------------------------------------------------
"UPDATE users SET usr_last_login = ? WHERE usr_id = ?"

"UPDATE users SET usr_last_login = 2017-05-08 13:43:20 WHERE usr_id = 1"

PUT http://localhost:8000/users/1? HTTP/1.1 {"usr_last_login ":" 2017-05-08 13:43:20"}


---------------------------------------------------------------------
"SELECT t0.usr_id AS usr_id_1, t0.usr_firstname AS usr_firstname_2, t0.usr_lastname AS usr_lastname_3, t0.usr_phone AS usr_phone_4, t0.usr_mobile AS usr_mobile_5, t0.usr_picture AS usr_picture_6, t0.usr_function AS usr_function_7, t0.usr_added_date AS usr_added_date_8, t0.usr_last_update_date AS usr_last_update_date_9, t0.usr_username AS usr_username_10, t0.usr_username_canonical AS usr_username_canonical_11, t0.usr_password_requested_at AS usr_password_requested_at_12, t0.usr_roles AS usr_roles_13, t0.usr_email AS usr_email_14, t0.usr_email_canonical AS usr_email_canonical_15, t0.usr_enabled AS usr_enabled_16, t0.usr_salt AS usr_salt_17, t0.usr_password AS usr_password_18, t0.usr_last_login AS usr_last_login_19, t0.usr_confirmation_token AS usr_confirmation_token_20, t0.usr_added_by AS usr_added_by_21, t0.usr_last_modified_by AS usr_last_modified_by_22, t0.usr_workspace AS usr_workspace_23 FROM users t0 WHERE t0.usr_id = ? LIMIT 1"

"SELECT t0.usr_id AS usr_id_1, t0.usr_firstname AS usr_firstname_2, t0.usr_lastname AS usr_lastname_3, t0.usr_phone AS usr_phone_4, t0.usr_mobile AS usr_mobile_5, t0.usr_picture AS usr_picture_6, t0.usr_function AS usr_function_7, t0.usr_added_date AS usr_added_date_8, t0.usr_last_update_date AS usr_last_update_date_9, t0.usr_username AS usr_username_10, t0.usr_username_canonical AS usr_username_canonical_11, t0.usr_password_requested_at AS usr_password_requested_at_12, t0.usr_roles AS usr_roles_13, t0.usr_email AS usr_email_14, t0.usr_email_canonical AS usr_email_canonical_15, t0.usr_enabled AS usr_enabled_16, t0.usr_salt AS usr_salt_17, t0.usr_password AS usr_password_18, t0.usr_last_login AS usr_last_login_19, t0.usr_confirmation_token AS usr_confirmation_token_20, t0.usr_added_by AS usr_added_by_21, t0.usr_last_modified_by AS usr_last_modified_by_22, t0.usr_workspace AS usr_workspace_23 FROM users t0 WHERE t0.usr_id = 1 LIMIT 1"

GET http://localhost:8000/users?usr_ HTTP/1.1


---------------------------------------------------------------------`

**Comment by SebHoremans** [comment] 2017-05-08 12:10
Found : 
In circle/doctrine-rest-driver/Circle/DoctrineRestDriver/Types/HttpQuery.php
the create function returns 
`return preg_replace('/id\=\d*&*/', '', $query);`

So it change my usr_id by usr_

**Comment by SebHoremans** [comment] 2017-05-08 12:15
I suggest to change it by
`return preg_replace('/^\id\=\d*&*/', '', $query);`
 to only change the string if it starts if "id="

**Comment by TobiasHauck** [comment] 2017-05-08 13:36
Should be even more generic. But this is the right place to make changes. We should find a way to inject the identifiers name here

**Comment by TobiasHauck** [comment] 2017-05-08 20:38
On my local branch the issue is fixed now. Will create a pull request tomorrow

**Comment by SebHoremans** [comment] 2017-05-09 08:10
Thanks a lot !

**Comment by TobiasHauck** [comment] 2017-05-12 06:54
Should be solved now - hopefully :-D

**Closed** 2017-05-12 06:54 UTC

**Comment by SebHoremans** [comment] 2017-05-15 07:50
Tested, it works perfectly ! 
Thanks for your work.

**Comment by TobiasHauck** [comment] 2017-05-15 08:19
ok awesome. I'll have a look at the other issue in a few days

**Comment by robwasripped** [comment] 2017-05-16 10:45
I've hit the same issue with the string "id=<int>" being stripped from queries. For me it's an issue with an `account_id` on a `User` object. I'm happy to submit a PR for this if you haven't the time yet to do so.

**Comment by TobiasHauck** [comment] 2017-05-16 15:30
would be great, thank you once again!
